services:
  mysql:
    image: mysql:9.1.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  piramida-app:
    build: .
    image: piramida-web-app:1.0.0cc
    container_name: piramida_web_app
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      PROD_DB_HOST: mysql
      PROD_DB_PORT: 3306
      PROD_DB_NAME: app_db
      PROD_DB_USERNAME: root
      PROD_DB_PASSWORD: root
    volumes:
      - app-images:/app/images

volumes:
  mysql-data:
  app-images: